ALTER TABLE "Config" ADD COLUMN "logRetentionDays" INTEGER NOT NULL DEFAULT 30;
ALTER TABLE "Config" ADD COLUMN "credentialRetentionDays" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Config" ADD COLUMN "mediaRetentionDays" INTEGER NOT NULL DEFAULT 30;
